"""Server-owned SVG and table runtime for deterministic data scenes."""

from __future__ import annotations

import html
import json
from typing import Any

from aetherviz_service.aetherviz.ir.data_distribution.contract import compile_data_distribution_ir


def assemble_data_distribution_business_html(ir: dict[str, Any], plan: dict[str, Any], topic: str) -> str:
    compiled = compile_data_distribution_ir(ir, plan)
    title = html.escape(str(plan.get("title") or topic or "数据与分布"))
    goal = html.escape(str(plan.get("goal") or "观察同一数据源在不同统计表征中的规律。"))
    observation = html.escape(str(ir.get("observation") or "比较图形与统计量的同步变化。"))
    animation = ir.get("animation") if isinstance(ir.get("animation"), dict) else {}
    variable = str(animation.get("variable") or "参数")
    variables = {
        str(item.get("name")): item
        for item in ((plan.get("interactive_spec") or {}).get("variables", []))
        if isinstance(item, dict) and item.get("name") and not item.get("computed")
    }
    meta = variables.get(variable, {})
    state_label = html.escape(str(meta.get("label") or variable))
    step = float(meta.get("step") or (float(animation.get("to", 1)) - float(animation.get("from", 0))) / 100)
    initial_state = {name: float(item.get("default", item.get("min", 0))) for name, item in variables.items()}
    initial_state[variable] = float(animation.get("default", animation.get("from", 0)))
    bounds = {
        name: {
            "min": float(item.get("min", 0)),
            "max": float(item.get("max", 1)),
            "default": float(item.get("default", item.get("min", 0))),
        }
        for name, item in variables.items()
    }
    initial_json = json.dumps(initial_state, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    bounds_json = json.dumps(bounds, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>
.dd{{font-family:Inter,"PingFang SC",sans-serif;color:#17352d;background:#f7fbf9;padding:18px}}.dd-head{{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}}.dd-head h1{{font-size:clamp(22px,3vw,34px);margin:0 0 6px}}.dd-head p{{margin:0;color:#526d65}}.dd-badge{{white-space:nowrap;padding:6px 10px;border-radius:999px;background:#e1f2ea;color:#176b54;font-size:13px}}.dd-layout{{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:16px;margin-top:14px}}.dd-stage,.dd-panel{{border:1px solid #d5e6df;border-radius:18px;background:#fff}}.dd-stage{{min-height:430px;padding:12px;overflow:auto}}#data-distribution-svg{{display:block;width:100%;min-height:405px}}#dd-table{{display:none;overflow:auto}}#dd-table table{{width:100%;border-collapse:collapse}}#dd-table th,#dd-table td{{padding:10px;border-bottom:1px solid #e3ece8;text-align:right}}#dd-table th:first-child,#dd-table td:first-child{{text-align:left}}.dd-panel{{padding:16px}}.dd-panel h2{{font-size:16px;margin:0 0 10px}}.dd-metrics{{display:grid;gap:8px}}.dd-metric{{padding:10px;border-radius:12px;background:#f1f7f4}}.dd-metric strong{{display:block;font-size:20px;color:#176b54}}.dd-caption{{line-height:1.65;color:#49625b}}.dd-controls{{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:14px}}.dd-controls input{{flex:1;min-width:170px}}.dd-chart-select{{padding:7px;border:1px solid #b9cec5;border-radius:9px;background:#fff}}.dd-axis{{stroke:#789087;stroke-width:1.4}}.dd-grid{{stroke:#e4ece8;stroke-width:1}}.dd-mark{{fill:#2c7a68;stroke:#fff;stroke-width:1.5}}.dd-line{{fill:none;stroke:#2c7a68;stroke-width:3}}.dd-regression{{stroke:#df7a45;stroke-width:2.5;stroke-dasharray:7 5}}.dd-box{{fill:#dff0e8;stroke:#2c7a68;stroke-width:2}}.dd-label{{font-size:12px;fill:#526d65}}@media(max-width:780px){{.dd-layout{{grid-template-columns:1fr}}.dd-stage{{min-height:360px}}#data-distribution-svg{{min-height:335px}}}}
</style></head><body><main class="dd"><header class="dd-head" data-region="learning-goal"><div><h1>{title}</h1><p>{goal}</p></div><span class="dd-badge">数据分布 IR</span></header><section class="dd-layout"><div class="dd-stage" id="aetherviz-stage"><svg id="data-distribution-svg" data-role="main-visual" viewBox="0 0 760 420" role="img" aria-label="统计数据图"></svg><div id="dd-table"></div></div><aside class="dd-panel" data-region="caption"><h2>确定性统计量</h2><div id="dd-metrics" class="dd-metrics"></div><p id="animation-caption" class="dd-caption">{observation}</p></aside></section><footer class="dd-controls control-panel" data-region="controls"><label for="dd-range">{state_label}</label><input id="dd-range" type="range" min="{float(animation.get("from", 0))}" max="{float(animation.get("to", 1))}" step="{step}"><output id="dd-output"></output><select id="dd-chart-select" class="dd-chart-select" aria-label="选择图表"></select><button id="play-animation" type="button">播放</button><button id="pause-animation" type="button">暂停</button><button id="reset-animation" type="button">重置</button><select id="dd-speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></footer><section data-region="formula"><p>表格、图形、分箱与统计读数共享同一组数据，派生量由服务端契约定义。</p></section></main>
<script id="data-distribution-ir" type="application/json">{compiled}</script><script>
(()=>{{'use strict';const IR=JSON.parse(document.getElementById('data-distribution-ir').textContent),BOUNDS={bounds_json},NS='http://www.w3.org/2000/svg',svg=document.getElementById('data-distribution-svg'),tableHost=document.getElementById('dd-table'),metricHost=document.getElementById('dd-metrics'),caption=document.getElementById('animation-caption'),range=document.getElementById('dd-range'),output=document.getElementById('dd-output'),chartSelect=document.getElementById('dd-chart-select'),state={initial_json};let controller=null;range.value=String(state[IR.animation.variable]);
function evaluate(expr){{if(typeof expr==='number')return expr;if(expr&&Object.prototype.hasOwnProperty.call(expr,'state'))return Number(state[expr.state]);const v=(expr.args||[]).map(evaluate);switch(expr.op){{case'add':return v.reduce((a,b)=>a+b,0);case'sub':return v.slice(1).reduce((a,b)=>a-b,v[0]);case'mul':return v.reduce((a,b)=>a*b,1);case'div':return v.slice(1).reduce((a,b)=>a/b,v[0]);case'pow':return Math.pow(v[0],v[1]);case'min':return Math.min(...v);case'max':return Math.max(...v);case'neg':return-v[0];case'abs':return Math.abs(v[0]);case'sqrt':return Math.sqrt(v[0]);case'round':return Math.round(v[0]);case'floor':return Math.floor(v[0]);case'ceil':return Math.ceil(v[0]);default:throw new Error('invalid_data_expression');}}}}
const numeric=new Set(IR.fields.filter(f=>f.type==='number').map(f=>f.id));function rows(){{return IR.rows.map(row=>{{const value={{__id:row.id}};row.cells.forEach(cell=>value[cell.field]=numeric.has(cell.field)?evaluate(cell.value):String(cell.value));return value;}});}}function quantile(values,p){{const sorted=[...values].sort((a,b)=>a-b),index=(sorted.length-1)*p,lo=Math.floor(index),hi=Math.ceil(index);return sorted[lo]+(sorted[hi]-sorted[lo])*(index-lo);}}function regression(data,xField,yField){{const xs=data.map(r=>r[xField]),ys=data.map(r=>r[yField]),xm=xs.reduce((a,b)=>a+b,0)/xs.length,ym=ys.reduce((a,b)=>a+b,0)/ys.length,den=xs.reduce((s,x)=>s+(x-xm)*(x-xm),0),slope=xs.reduce((s,x,i)=>s+(x-xm)*(ys[i]-ym),0)/den,intercept=ym-slope*xm,total=ys.reduce((s,y)=>s+(y-ym)*(y-ym),0),res=ys.reduce((s,y,i)=>s+(y-(slope*xs[i]+intercept))**2,0);return{{slope,intercept,r_squared:total?1-res/total:1}};}}function metricValue(metric,data){{if(metric.type==='linear_regression')return regression(data,metric.x_field,metric.y_field);const v=data.map(r=>Number(r[metric.field])).sort((a,b)=>a-b),mean=v.reduce((a,b)=>a+b,0)/v.length;if(metric.type==='count')return v.length;if(metric.type==='sum')return v.reduce((a,b)=>a+b,0);if(metric.type==='mean')return mean;if(metric.type==='median')return quantile(v,.5);if(metric.type==='variance'||metric.type==='standard_deviation'){{const divisor=metric.sample?Math.max(1,v.length-1):v.length,variance=v.reduce((s,x)=>s+(x-mean)*(x-mean),0)/divisor;return metric.type==='variance'?variance:Math.sqrt(variance);}}if(metric.type==='minimum')return Math.min(...v);if(metric.type==='maximum')return Math.max(...v);if(metric.type==='q1')return quantile(v,.25);if(metric.type==='q3')return quantile(v,.75);if(metric.type==='iqr')return quantile(v,.75)-quantile(v,.25);throw new Error('invalid_metric');}}
function el(tag,attrs,parent=svg){{const node=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs||{{}}))node.setAttribute(key,String(value));parent.appendChild(node);return node;}}function text(x,y,value,anchor='middle'){{const node=el('text',{{x,y,class:'dd-label','text-anchor':anchor}});node.textContent=String(value);return node;}}function extent(values){{let low=Math.min(...values),high=Math.max(...values);if(low===high){{low-=1;high+=1;}}const pad=(high-low)*.08;return[low-pad,high+pad];}}function frame(xValues,yValues){{const[x0,x1]=extent(xValues),[y0,y1]=extent(yValues),left=58,right=735,top=28,bottom=375,X=x=>left+(x-x0)/(x1-x0)*(right-left),Y=y=>bottom-(y-y0)/(y1-y0)*(bottom-top);for(let i=0;i<=5;i++){{const y=top+(bottom-top)*i/5;el('line',{{x1:left,y1:y,x2:right,y2:y,class:'dd-grid'}});text(left-8,y+4,(y1-(y1-y0)*i/5).toFixed(1),'end');}}el('line',{{x1:left,y1:bottom,x2:right,y2:bottom,class:'dd-axis'}});el('line',{{x1:left,y1:top,x2:left,y2:bottom,class:'dd-axis'}});return{{X,Y,left,right,top,bottom,x0,x1,y0,y1}};}}
function renderTable(data){{svg.style.display='none';tableHost.style.display='block';tableHost.replaceChildren();const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');IR.fields.forEach(field=>{{const th=document.createElement('th');th.textContent=field.label+(field.unit?'（'+field.unit+'）':'');tr.appendChild(th);}});head.appendChild(tr);table.appendChild(head);const body=document.createElement('tbody');data.forEach(row=>{{const line=document.createElement('tr');IR.fields.forEach(field=>{{const td=document.createElement('td');td.textContent=numeric.has(field.id)?Number(row[field.id]).toFixed(2):String(row[field.id]);line.appendChild(td);}});body.appendChild(line);}});table.appendChild(body);tableHost.appendChild(table);}}
function renderBar(chart,data){{const categories=data.map(r=>String(r[chart.category_field])),values=data.map(r=>Number(r[chart.value_field])),f=frame(data.map((_,i)=>i),[0,...values]),band=(f.right-f.left)/data.length;data.forEach((row,i)=>{{const y=f.Y(values[i]);el('rect',{{x:f.left+i*band+band*.14,y,width:band*.72,height:f.bottom-y,rx:4,class:'dd-mark'}});text(f.left+(i+.5)*band,f.bottom+18,categories[i]);}});}}
function renderXY(chart,data){{const xs=data.map(r=>Number(r[chart.x_field])),ys=data.map(r=>Number(r[chart.y_field])),f=frame(xs,ys),points=data.map(r=>[f.X(r[chart.x_field]),f.Y(r[chart.y_field])]);if(chart.type==='line')el('path',{{d:points.map((p,i)=>(i?'L ':'M ')+p[0]+' '+p[1]).join(' '),class:'dd-line'}});points.forEach(p=>el('circle',{{cx:p[0],cy:p[1],r:5,class:'dd-mark'}}));const metric=IR.metrics.find(m=>m.type==='linear_regression'&&m.x_field===chart.x_field&&m.y_field===chart.y_field);if(chart.type==='scatter'&&metric){{const fit=regression(data,chart.x_field,chart.y_field);el('line',{{x1:f.X(f.x0),y1:f.Y(fit.slope*f.x0+fit.intercept),x2:f.X(f.x1),y2:f.Y(fit.slope*f.x1+fit.intercept),class:'dd-regression'}});}}}}
function renderHistogram(chart,data){{const values=data.map(r=>Number(r[chart.value_field])),width=evaluate(chart.bin_width),start=Math.floor(Math.min(...values)/width)*width,end=Math.ceil(Math.max(...values)/width)*width,bins=[];for(let edge=start;edge<end+width*.5;edge+=width)bins.push({{edge,count:0}});values.forEach(value=>{{const index=Math.min(bins.length-1,Math.floor((value-start)/width));bins[index].count++;}});const f=frame(bins.map((_,i)=>i),[0,...bins.map(b=>b.count)]),band=(f.right-f.left)/bins.length;bins.forEach((bin,i)=>{{const y=f.Y(bin.count);el('rect',{{x:f.left+i*band+1,y,width:Math.max(1,band-2),height:f.bottom-y,class:'dd-mark'}});text(f.left+(i+.5)*band,f.bottom+18,bin.edge.toFixed(1));}});}}
function renderBox(chart,data){{const key=chart.group_field||'__all',groups=new Map();data.forEach(row=>{{const name=key==='__all'?'全部':String(row[key]);if(!groups.has(name))groups.set(name,[]);groups.get(name).push(Number(row[chart.value_field]));}});const all=[...groups.values()].flat(),f=frame([...groups.keys()].map((_,i)=>i),all),band=(f.right-f.left)/groups.size;[...groups.entries()].forEach(([name,values],i)=>{{values.sort((a,b)=>a-b);const min=values[0],q1=quantile(values,.25),med=quantile(values,.5),q3=quantile(values,.75),max=values[values.length-1],x=f.left+(i+.5)*band;el('line',{{x1:x,y1:f.Y(min),x2:x,y2:f.Y(max),class:'dd-axis'}});el('rect',{{x:x-band*.22,y:f.Y(q3),width:band*.44,height:Math.max(2,f.Y(q1)-f.Y(q3)),class:'dd-box'}});el('line',{{x1:x-band*.22,y1:f.Y(med),x2:x+band*.22,y2:f.Y(med),class:'dd-axis'}});text(x,f.bottom+18,name);}});}}
function renderMetrics(data){{metricHost.replaceChildren();IR.metrics.forEach(metric=>{{const value=metricValue(metric,data),box=document.createElement('div'),label=document.createElement('span'),strong=document.createElement('strong');box.className='dd-metric';label.textContent=metric.label;strong.textContent=typeof value==='object'?'y = '+value.slope.toFixed(metric.precision)+'x '+(value.intercept>=0?'+ ':'− ')+Math.abs(value.intercept).toFixed(metric.precision)+'，R²='+value.r_squared.toFixed(metric.precision):Number(value).toFixed(metric.precision);box.append(label,strong);metricHost.appendChild(box);}});}}
function render(){{const data=rows(),chart=IR.charts.find(item=>item.id===chartSelect.value)||IR.charts[0];svg.replaceChildren();svg.style.display='block';tableHost.style.display='none';if(chart.type==='table')renderTable(data);else if(chart.type==='bar')renderBar(chart,data);else if(chart.type==='line'||chart.type==='scatter')renderXY(chart,data);else if(chart.type==='histogram')renderHistogram(chart,data);else if(chart.type==='box')renderBox(chart,data);if(chart.type!=='table')text(380,18,chart.title);renderMetrics(data);range.value=String(state[IR.animation.variable]);output.value=Number(state[IR.animation.variable]).toFixed(2);caption.textContent=IR.observation+' 当前参数：'+output.value;}}
function clamp(name,value){{const b=BOUNDS[name];return b?Math.max(b.min,Math.min(b.max,value)):value;}}function setProgress(progress){{state[IR.animation.variable]=IR.animation.from+(IR.animation.to-IR.animation.from)*Math.max(0,Math.min(1,progress));render();}}function play(){{controller.play();}}function pause(){{controller.pause();}}function reset(){{controller.reset();for(const[name,b]of Object.entries(BOUNDS))state[name]=b.default;render();}}function setSpeed(value){{controller.setSpeed(Math.max(.25,Math.min(4,Number(value)||1)));}}function update(patch){{if(patch&&typeof patch==='object')for(const[key,value]of Object.entries(patch))if(Object.prototype.hasOwnProperty.call(state,key))state[key]=clamp(key,Number(value));if(patch&&patch.speed!=null)setSpeed(patch.speed);render();}}function getState(){{return{{...state,chart:chartSelect.value}};}}function handleWidgetAction(event){{const data=event.data||{{}};if(data.type==='SET_WIDGET_STATE')update(data.state||data.payload||{{}});else if(data.type==='ANNOTATE_ELEMENT')caption.textContent=String(data.text||data.annotation||caption.textContent);}}
try{{IR.charts.forEach(chart=>{{const option=document.createElement('option');option.value=chart.id;option.textContent=chart.title;chartSelect.appendChild(option);}});if(!window.AetherVizAnimationController)throw new Error('missing_animation_controller');controller=window.AetherVizAnimationController.create({{duration:Number(IR.animation.duration)||6,update:setProgress}});range.addEventListener('input',()=>{{controller.pause();state[IR.animation.variable]=Number(range.value);render();}});chartSelect.addEventListener('change',render);document.getElementById('play-animation').addEventListener('click',play);document.getElementById('pause-animation').addEventListener('click',pause);document.getElementById('reset-animation').addEventListener('click',reset);document.getElementById('dd-speed').addEventListener('change',event=>setSpeed(event.target.value));window.addEventListener('message',handleWidgetAction);window.AetherVizRuntime={{play,pause,reset,setSpeed,update,getState}};render();window.__AETHERVIZ_RUNTIME_READY__=true;}}catch(error){{window.__AETHERVIZ_RUNTIME_ERROR__=String(error&&error.message||error);caption.textContent='课件初始化失败：'+window.__AETHERVIZ_RUNTIME_ERROR__;}}
}})();</script></body></html>"""
