services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UV_PROJECT_ENVIRONMENT: /opt/venv
      UV_LINK_MODE: copy
    ports:
      - "10095:10095"
    env_file:
      - .env
    restart: unless-stopped
