"""Server-owned SVG runtime for interactive number-line scenes."""

from __future__ import annotations

import html
import json
from typing import Any

from aetherviz_service.aetherviz.ir.number_line.contract import compile_number_line_ir


def assemble_number_line_business_html(ir: dict[str, Any], plan: dict[str, Any], topic: str) -> str:
    compiled = compile_number_line_ir(ir, plan)
    title = html.escape(str(topic or "数轴互动"))
    goal = html.escape(str(plan.get("goal") or "通过数轴观察数、区间和运算关系"))
    variables = _variables(plan)
    defaults = {item["name"]: item["default"] for item in variables}
    config = json.dumps(
        {"type": str(plan.get("interactive_type") or "simulation"), "version": "1.0", "defaults": {**defaults, "speed": 1}},
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")
    variable_config = json.dumps(variables, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    return f"""<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>
*{{box-sizing:border-box}}body{{margin:0;background:#f7f9fc;color:#172033;font-family:Inter,"PingFang SC",sans-serif}}.nl{{min-height:560px;display:grid;grid-template-rows:auto 1fr auto;gap:12px;padding:16px}}.nl-head{{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}}h1{{font-size:22px;margin:0 0 5px}}.goal{{margin:0;color:#526077;font-size:14px}}.badge{{padding:6px 10px;border-radius:999px;background:#e6f7f4;color:#087f6d;font-size:12px;white-space:nowrap}}.stage{{min-width:0;border:1px solid #dbe3f0;border-radius:16px;background:#fff;overflow:hidden}}svg{{display:block;width:100%;height:100%;min-height:370px}}.controls{{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:end}}.sliders{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:9px}}.slider{{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;padding:8px 10px;border:1px solid #dbe3f0;border-radius:10px;background:#fff}}.slider label{{font-size:13px;color:#526077}}.slider output{{min-width:42px;text-align:right;font-variant-numeric:tabular-nums}}.buttons{{display:flex;flex-wrap:wrap;gap:7px}}button,select{{border:1px solid #cbd5e1;background:#fff;color:#26354e;border-radius:9px;padding:8px 11px;cursor:pointer}}button:hover{{background:#eef3f8}}.caption{{margin:0;padding:9px 12px;border-radius:10px;background:#eef8f6;color:#315b54;font-size:13px}}@media(max-width:720px){{.controls{{grid-template-columns:1fr}}.buttons{{justify-content:flex-start}}}}
</style></head><body><main class="nl"><header class="nl-head" data-region="learning-goal"><div><h1>{title}</h1><p class="goal">{goal}</p></div><span class="badge">数轴 IR</span></header><section class="stage" id="aetherviz-stage"><svg id="number-line" data-role="main-visual" viewBox="0 0 960 500" role="img" aria-label="互动数轴"><defs><marker id="arrow-right" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/></marker></defs><g id="tracks"></g><g id="objects"></g></svg></section><section class="controls" data-region="controls"><div class="sliders" id="state-controls"></div><div class="buttons"><button id="play-animation" type="button">播放</button><button id="pause-animation" type="button">暂停</button><button id="reset-animation" type="button">重置</button><select id="speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></div></section><p id="observation" class="caption" data-region="caption">调节参数，观察数轴对象及其数学关系如何同步变化。</p><section data-region="formula"><p>所有位置均由数学值经过同一数轴映射得到。</p></section><ol data-region="teaching-flow"><li data-step="1">识别数轴和端点</li><li data-step="2">调节参数或播放动画</li><li data-step="3">比较位置、方向与距离关系</li></ol></main>
<script id="widget-config" type="application/json">{config}</script><script id="number-line-variables" type="application/json">{variable_config}</script><script id="number-line-ir" type="application/json">{compiled}</script>
<script>
(()=>{{'use strict';const IR=JSON.parse(document.getElementById('number-line-ir').textContent);const VARIABLES=JSON.parse(document.getElementById('number-line-variables').textContent);const NS='http://www.w3.org/2000/svg';const left=90,right=910;const state=Object.fromEntries(VARIABLES.map(v=>[v.name,Number(v.default)]));let controller=null,speed=1;const registry=new Map();const svg=(name,attrs={{}})=>{{const node=document.createElementNS(NS,name);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,String(value)));return node;}};const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
function evaluate(expr){{if(typeof expr==='number')return expr;if(expr&&typeof expr==='object'&&Object.prototype.hasOwnProperty.call(expr,'state'))return Number(state[expr.state]);const values=(expr.args||[]).map(evaluate);switch(expr.op){{case'add':return values.reduce((a,b)=>a+b,0);case'sub':return values.slice(1).reduce((a,b)=>a-b,values[0]);case'mul':return values.reduce((a,b)=>a*b,1);case'div':return values.slice(1).reduce((a,b)=>a/b,values[0]);case'min':return Math.min(...values);case'max':return Math.max(...values);case'neg':return-values[0];case'abs':return Math.abs(values[0]);default:throw new Error('invalid_number_line_expression');}}}}
function x(value){{return left+(clamp(value,IR.domain[0],IR.domain[1])-IR.domain[0])/(IR.domain[1]-IR.domain[0])*(right-left);}}function trackY(id){{const index=IR.tracks.findIndex(item=>item.id===id);return 105+(index+.5)*(330/IR.tracks.length);}}function textNode(label){{const node=svg('text',{{'text-anchor':'middle','font-size':14,fill:'#334155'}});node.textContent=label||'';return node;}}
function buildTracks(){{const root=document.getElementById('tracks');IR.tracks.forEach(track=>{{const y=trackY(track.id);root.appendChild(svg('line',{{x1:left,y1:y,x2:right,y2:y,stroke:'#64748b','stroke-width':2}}));const title=textNode(track.label);title.setAttribute('x',left);title.setAttribute('y',y-34);title.setAttribute('text-anchor','start');title.setAttribute('font-weight','600');root.appendChild(title);const ticks=10;for(let i=0;i<=ticks;i++){{const value=IR.domain[0]+(IR.domain[1]-IR.domain[0])*i/ticks;const px=x(value);root.appendChild(svg('line',{{x1:px,y1:y-6,x2:px,y2:y+6,stroke:'#94a3b8','stroke-width':1.5}}));const label=textNode(Number(value.toFixed(3)).toString());label.setAttribute('x',px);label.setAttribute('y',y+25);label.setAttribute('font-size','12');root.appendChild(label);}}}});}}
function addVisual(kind,item){{const root=document.getElementById('objects');const group=svg('g',{{'data-object':item.id,'data-kind':kind}});const color=item.color||'#0f766e';if(kind==='point'){{group.appendChild(svg('circle',{{r:7,stroke:color,'stroke-width':3}}));group.appendChild(textNode(item.label));}}else if(kind==='interval'){{group.appendChild(svg('line',{{stroke:color,'stroke-width':8,'stroke-linecap':'round'}}));group.appendChild(svg('circle',{{r:7,stroke:color,'stroke-width':3}}));group.appendChild(svg('circle',{{r:7,stroke:color,'stroke-width':3}}));group.appendChild(textNode(item.label));}}else if(kind==='derived_set'){{group.setAttribute('data-segment-count','0');}}else if(kind==='ray'){{group.appendChild(svg('line',{{stroke:color,'stroke-width':7,'stroke-linecap':'round','marker-end':'url(#arrow-right)'}}));group.appendChild(svg('circle',{{r:7,stroke:color,'stroke-width':3}}));group.appendChild(textNode(item.label));}}else if(kind==='distance'){{group.appendChild(svg('line',{{stroke:color,'stroke-width':3}}));group.appendChild(svg('line',{{stroke:color,'stroke-width':2}}));group.appendChild(svg('line',{{stroke:color,'stroke-width':2}}));group.appendChild(textNode(item.label));}}else{{group.appendChild(svg('line',{{stroke:color,'stroke-width':4,'marker-end':'url(#arrow-right)'}}));group.appendChild(svg('circle',{{r:5,fill:color}}));group.appendChild(textNode(item.label));}}root.appendChild(group);registry.set(item.id,group);}}
function buildObjects(){{IR.points.forEach(item=>addVisual('point',item));IR.intervals.forEach(item=>addVisual('interval',item));IR.derived_sets.forEach(item=>addVisual('derived_set',item));IR.rays.forEach(item=>addVisual('ray',item));IR.distances.forEach(item=>addVisual('distance',item));IR.movements.forEach(item=>addVisual('movement',item));}}
function intervalValue(item){{return{{start:evaluate(item.start),end:evaluate(item.end),left_endpoint:item.left_endpoint,right_endpoint:item.right_endpoint}};}}function contains(segment,value){{const epsilon=1e-9;const leftOk=value>segment.start+epsilon||(segment.left_endpoint==='closed'&&Math.abs(value-segment.start)<=epsilon);const rightOk=value<segment.end-epsilon||(segment.right_endpoint==='closed'&&Math.abs(value-segment.end)<=epsilon);return leftOk&&rightOk;}}
function deriveSegments(item){{const byId=new Map(IR.intervals.map(interval=>[interval.id,intervalValue(interval)]));const a=byId.get(item.inputs[0]),b=byId.get(item.inputs[1]);if(item.operation==='intersection'){{const start=Math.max(a.start,b.start),end=Math.min(a.end,b.end);if(start>end)return[];const included=contains(a,start)&&contains(b,start);if(start===end)return included?[{{start,end,left_endpoint:'closed',right_endpoint:'closed'}}]:[];return[{{start,end,left_endpoint:included?'closed':'open',right_endpoint:contains(a,end)&&contains(b,end)?'closed':'open'}}];}}const ordered=[a,b].sort((first,second)=>first.start-second.start||(first.left_endpoint==='closed'?-1:1));const first=ordered[0],second=ordered[1],touches=first.end>second.start||(Math.abs(first.end-second.start)<=1e-9&&(first.right_endpoint==='closed'||second.left_endpoint==='closed'));if(!touches)return ordered;if(second.start===first.start)first.left_endpoint=first.left_endpoint==='closed'||second.left_endpoint==='closed'?'closed':'open';if(second.end>first.end){{first.end=second.end;first.right_endpoint=second.right_endpoint;}}else if(Math.abs(second.end-first.end)<=1e-9)first.right_endpoint=first.right_endpoint==='closed'||second.right_endpoint==='closed'?'closed':'open';return[first];}}
function renderDerivedSet(item){{const group=registry.get(item.id),segments=deriveSegments(item),y=trackY(item.track),color=item.color||'#0f766e';group.replaceChildren();group.setAttribute('data-segment-count',String(segments.length));segments.forEach((segment,index)=>{{const a=x(segment.start),b=x(segment.end),line=svg('line',{{x1:a,y1:y,x2:b,y2:y,stroke:color,'stroke-width':8,'stroke-linecap':'round'}}),leftNode=svg('circle',{{cx:a,cy:y,r:7,stroke:color,'stroke-width':3}}),rightNode=svg('circle',{{cx:b,cy:y,r:7,stroke:color,'stroke-width':3}}),label=textNode(segments.length>1?item.label+' '+(index+1):item.label);endpoint(leftNode,segment.left_endpoint,color);endpoint(rightNode,segment.right_endpoint,color);label.setAttribute('x',(a+b)/2);label.setAttribute('y',y-18);group.append(line,leftNode,rightNode,label);}});}}
function endpoint(node,style,color){{node.setAttribute('fill',style==='closed'?color:'#fff');}}function updateVisual(kind,item){{const group=registry.get(item.id),nodes=group.children,y=trackY(item.track),color=item.color||'#0f766e';if(kind==='point'){{const px=x(evaluate(item.value));nodes[0].setAttribute('cx',px);nodes[0].setAttribute('cy',y);endpoint(nodes[0],item.endpoint,color);nodes[1].setAttribute('x',px);nodes[1].setAttribute('y',y-18);}}else if(kind==='interval'){{const a=x(evaluate(item.start)),b=x(evaluate(item.end));Object.entries({{x1:a,y1:y,x2:b,y2:y}}).forEach(([k,v])=>nodes[0].setAttribute(k,v));nodes[1].setAttribute('cx',a);nodes[1].setAttribute('cy',y);endpoint(nodes[1],item.left_endpoint,color);nodes[2].setAttribute('cx',b);nodes[2].setAttribute('cy',y);endpoint(nodes[2],item.right_endpoint,color);nodes[3].setAttribute('x',(a+b)/2);nodes[3].setAttribute('y',y-18);}}else if(kind==='ray'){{const boundary=x(evaluate(item.boundary)),edge=item.direction==='left'?left:right;const start=item.direction==='left'?boundary:boundary,end=item.direction==='left'?edge:edge;Object.entries({{x1:start,y1:y,x2:end,y2:y}}).forEach(([k,v])=>nodes[0].setAttribute(k,v));nodes[0].setAttribute('marker-end',item.direction==='right'?'url(#arrow-right)':'');nodes[0].setAttribute('marker-start',item.direction==='left'?'url(#arrow-right)':'');nodes[1].setAttribute('cx',boundary);nodes[1].setAttribute('cy',y);endpoint(nodes[1],item.endpoint,color);nodes[2].setAttribute('x',(boundary+edge)/2);nodes[2].setAttribute('y',y-18);}}else if(kind==='distance'){{const a=x(evaluate(item.start)),b=x(evaluate(item.end)),dy=y-22;Object.entries({{x1:a,y1:dy,x2:b,y2:dy}}).forEach(([k,v])=>nodes[0].setAttribute(k,v));Object.entries({{x1:a,y1:dy-6,x2:a,y2:dy+6}}).forEach(([k,v])=>nodes[1].setAttribute(k,v));Object.entries({{x1:b,y1:dy-6,x2:b,y2:dy+6}}).forEach(([k,v])=>nodes[2].setAttribute(k,v));nodes[3].setAttribute('x',(a+b)/2);nodes[3].setAttribute('y',dy-8);nodes[3].textContent=(item.label?item.label+' = ':'')+Math.abs(evaluate(item.end)-evaluate(item.start)).toFixed(2);}}else{{const a=x(evaluate(item.start)),b=x(evaluate(item.start)+evaluate(item.delta)),dy=y-20;Object.entries({{x1:a,y1:dy,x2:b,y2:dy}}).forEach(([k,v])=>nodes[0].setAttribute(k,v));nodes[1].setAttribute('cx',a);nodes[1].setAttribute('cy',dy);nodes[2].setAttribute('x',(a+b)/2);nodes[2].setAttribute('y',dy-10);nodes[2].textContent=(item.label||'位移')+' '+(evaluate(item.delta)>=0?'+':'')+evaluate(item.delta).toFixed(2);}}}}
function render(){{IR.points.forEach(item=>updateVisual('point',item));IR.intervals.forEach(item=>updateVisual('interval',item));IR.derived_sets.forEach(renderDerivedSet);IR.rays.forEach(item=>updateVisual('ray',item));IR.distances.forEach(item=>updateVisual('distance',item));IR.movements.forEach(item=>updateVisual('movement',item));VARIABLES.forEach(variable=>{{const input=document.querySelector('[data-state="'+variable.name+'"] input');const output=document.querySelector('[data-state="'+variable.name+'"] output');if(input)input.value=String(state[variable.name]);if(output)output.value=Number(state[variable.name]).toFixed(variable.step<1?2:0)+(variable.unit||'');}});}}
function buildControls(){{const root=document.getElementById('state-controls');VARIABLES.forEach(variable=>{{const wrap=document.createElement('div');wrap.className='slider';wrap.dataset.state=variable.name;const label=document.createElement('label');label.textContent=variable.label||variable.name;const input=document.createElement('input');input.type='range';input.min=variable.min;input.max=variable.max;input.step=variable.step;const output=document.createElement('output');input.addEventListener('input',()=>{{controller.pause();state[variable.name]=Number(input.value);render();}});wrap.append(label,input,output);root.appendChild(wrap);}});}}
function setProgress(progress){{const frames=IR.animation.keyframes||[];if(frames.length>=2){{let rightFrame=frames.findIndex(frame=>frame.progress>=progress);if(rightFrame<=0)rightFrame=1;const a=frames[rightFrame-1],b=frames[Math.min(rightFrame,frames.length-1)],local=(progress-a.progress)/Math.max(.000001,b.progress-a.progress);Object.keys(a.state).forEach(name=>{{state[name]=a.state[name]+(b.state[name]-a.state[name])*clamp(local,0,1);}});}}else{{const name=IR.animation.variable;state[name]=evaluate(IR.animation.from)+(evaluate(IR.animation.to)-evaluate(IR.animation.from))*clamp(progress,0,1);}}render();}}function play(){{controller.play();}}function pause(){{controller.pause();}}function reset(){{controller.reset();VARIABLES.forEach(variable=>state[variable.name]=Number(variable.default));render();}}function setSpeed(value){{speed=clamp(Number(value)||1,.25,4);controller.setSpeed(speed);}}function update(patch){{if(patch)VARIABLES.forEach(variable=>{{if(Object.prototype.hasOwnProperty.call(patch,variable.name))state[variable.name]=clamp(Number(patch[variable.name]),variable.min,variable.max);}});if(patch&&patch.speed!=null)setSpeed(patch.speed);render();}}function getState(){{return{{...state,speed}};}}function handleWidgetAction(event){{const data=event.data||{{}};if(data.type==='SET_WIDGET_STATE')update(data.state||data.payload||{{}});else if(data.type==='HIGHLIGHT_ELEMENT'){{const node=document.querySelector(data.selector||'');if(node)node.style.filter='drop-shadow(0 0 6px #f59e0b)';}}else if(data.type==='ANNOTATE_ELEMENT')document.getElementById('observation').textContent=String(data.text||data.annotation||'');else if(data.type==='REVEAL_ELEMENT'){{const node=document.querySelector(data.selector||'');if(node)node.hidden=false;}}}}
buildTracks();buildObjects();buildControls();if(!window.AetherVizAnimationController)throw new Error('missing_animation_controller');controller=window.AetherVizAnimationController.create({{duration:Number(IR.animation.duration)||6,update:setProgress}});document.getElementById('play-animation').addEventListener('click',play);document.getElementById('pause-animation').addEventListener('click',pause);document.getElementById('reset-animation').addEventListener('click',reset);document.getElementById('speed').addEventListener('change',event=>setSpeed(event.target.value));window.addEventListener('message',handleWidgetAction);window.AetherVizRuntime={{play,pause,reset,setSpeed,update,getState}};render();window.__AETHERVIZ_RUNTIME_READY__=true;
}})();
</script></body></html>"""


def _variables(plan: dict[str, Any]) -> list[dict[str, Any]]:
    spec = plan.get("interactive_spec") if isinstance(plan.get("interactive_spec"), dict) else {}
    result: list[dict[str, Any]] = []
    for item in spec.get("variables", []):
        if not isinstance(item, dict) or item.get("computed") or not item.get("name"):
            continue
        try:
            result.append(
                {
                    "name": str(item["name"]),
                    "label": str(item.get("label") or item["name"]),
                    "min": float(item.get("min", 0)),
                    "max": float(item.get("max", 1)),
                    "default": float(item.get("default", 0)),
                    "step": float(item.get("step", 0.1)),
                    "unit": str(item.get("unit") or ""),
                }
            )
        except (TypeError, ValueError):
            continue
    return result
