"""Pure size and output-budget limits shared by settings and workflows."""

from __future__ import annotations

import math

MODEL_HTML_TARGET_CHARS = 38_000
MODEL_HTML_HARD_LIMIT_CHARS = 42_000
ASSEMBLED_HTML_SAFETY_LIMIT_CHARS = 64_000
MAX_FUNCTION_REPLACEMENTS = 5
MAX_FUNCTION_REPLACEMENT_CHARS = 6_000
MIN_MODEL_HTML_CHARS = 150

FULL_HTML_OUTPUT_RESERVE_CHARS = 2_048
ESTIMATED_OUTPUT_CHARS_PER_TOKEN = 3
MIN_FULL_HTML_OUTPUT_TOKENS = math.ceil(
    (MODEL_HTML_HARD_LIMIT_CHARS + FULL_HTML_OUTPUT_RESERVE_CHARS)
    / ESTIMATED_OUTPUT_CHARS_PER_TOKEN
)


def estimated_output_capacity_chars(max_tokens: int) -> int:
    return max(max_tokens, 512) * ESTIMATED_OUTPUT_CHARS_PER_TOKEN
