"""Server-owned reveal runtime for validated symbolic derivations."""

from __future__ import annotations

import html
from typing import Any

from aetherviz_service.aetherviz.ir.symbolic_derivation.contract import compile_symbolic_derivation_ir


def assemble_symbolic_derivation_business_html(ir: dict[str, Any], plan: dict[str, Any], topic: str) -> str:
    compiled = compile_symbolic_derivation_ir(ir, plan)
    title = html.escape(str(plan.get("title") or topic or "符号推导"))
    goal = html.escape(str(plan.get("goal") or "逐步观察等价变换，并说明每一步依据。"))
    observation = html.escape(str(ir.get("observation") or "每一步均由服务端验证等价性。"))
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>
.sd{{font-family:Inter,"PingFang SC",sans-serif;color:#20243a;background:#f6f7fc;padding:20px;min-height:100vh;box-sizing:border-box}}.sd h1{{margin:0;font-size:clamp(24px,4vw,38px)}}.sd-goal{{color:#626a86}}.sd-layout{{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:18px}}.sd-stage,.sd-side{{background:#fff;border:1px solid #dfe2ef;border-radius:18px;padding:18px}}.sd-step{{display:grid;grid-template-columns:40px 1fr;gap:12px;padding:14px 0;border-bottom:1px solid #eceef6;opacity:.25;transform:translateY(8px);transition:.25s}}.sd-step.visible{{opacity:1;transform:none}}.sd-index{{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#555ee8;color:white}}.sd-formula{{font:600 clamp(17px,2.5vw,25px)/1.5 ui-monospace,SFMono-Regular,monospace;overflow-wrap:anywhere}}.sd-rule{{color:#666f8b;font-size:14px}}.sd-controls{{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:16px}}button,input{{accent-color:#555ee8}}button{{border:0;border-radius:9px;padding:9px 14px;background:#e9eafd;color:#343ba8;cursor:pointer}}@media(max-width:760px){{.sd-layout{{grid-template-columns:1fr}}}}
</style></head><body><main class="sd"><header data-region="learning-goal"><h1>{title}</h1><p class="sd-goal">{goal}</p></header><section class="sd-layout"><div class="sd-stage" id="aetherviz-stage" data-role="main-visual"><div id="sd-steps"></div></div><aside class="sd-side" data-region="caption"><h2>验证说明</h2><p id="animation-caption">{observation}</p><p>等式按“左式 − 右式”的规范多项式比较；等式两侧允许同时乘除已声明的非零常数。</p></aside></section><footer class="sd-controls control-panel" data-region="controls"><label for="sd-range">推导进度</label><input id="sd-range" type="range" min="0" max="1" step="0.001" value="0"><output id="sd-output">1</output><button id="play-animation">播放</button><button id="pause-animation">暂停</button><button id="reset-animation">重置</button><select id="sd-speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></footer></main><script id="symbolic-derivation-ir" type="application/json">{compiled}</script><script>
(()=>{{'use strict';const IR=JSON.parse(document.getElementById('symbolic-derivation-ir').textContent),stepsEl=document.getElementById('sd-steps'),range=document.getElementById('sd-range'),output=document.getElementById('sd-output'),caption=document.getElementById('animation-caption');let controller,progress=0;
function precedence(expr){{return typeof expr==='number'?9:expr.symbol?9:expr.op==='pow'?8:expr.op==='neg'?7:expr.op==='mul'?6:5}}function format(expr,parent=0){{if(typeof expr==='number')return String(expr);if(expr.symbol)return expr.symbol;const p=precedence(expr);let value;if(expr.op==='add')value=expr.args.map(arg=>format(arg,p)).join(' + ').replaceAll('+ -','− ');else if(expr.op==='mul')value=expr.args.map(arg=>format(arg,p)).join(' · ');else if(expr.op==='neg')value='−'+format(expr.args[0],p);else value=format(expr.args[0],p)+'^'+format(expr.args[1],p);return p<parent?'('+value+')':value}}function relation(item){{return format(item.left)+' = '+format(item.right)}}function build(){{IR.steps.forEach((step,index)=>{{const row=document.createElement('article');row.className='sd-step';row.innerHTML='<span class="sd-index">'+(index+1)+'</span><div><div class="sd-formula"></div><div class="sd-rule"></div></div>';row.querySelector('.sd-formula').textContent=relation(step.after);row.querySelector('.sd-rule').textContent=step.explanation+'｜'+step.rule;stepsEl.appendChild(row)}})}}function render(){{const count=Math.max(1,Math.ceil(progress*IR.steps.length));Array.from(stepsEl.children).forEach((node,index)=>node.classList.toggle('visible',index<count));range.value=String(progress);output.value=String(count)+' / '+IR.steps.length;caption.textContent=IR.observation+' 当前显示第 '+count+' 步。'}}function setProgress(value){{progress=Math.max(0,Math.min(1,Number(value)||0));render()}}function play(){{controller.play()}}function pause(){{controller.pause()}}function reset(){{controller.reset();progress=0;render()}}function setSpeed(value){{controller.setSpeed(Math.max(.25,Math.min(4,Number(value)||1)))}}function update(patch){{if(patch&&patch.progress!=null)setProgress(patch.progress);if(patch&&patch.speed!=null)setSpeed(patch.speed)}}function getState(){{return{{progress,visibleSteps:Math.max(1,Math.ceil(progress*IR.steps.length))}}}}
try{{build();if(!window.AetherVizAnimationController)throw new Error('missing_animation_controller');controller=window.AetherVizAnimationController.create({{duration:Math.max(4,IR.steps.length*.8),update:setProgress}});range.addEventListener('input',()=>{{pause();setProgress(range.value)}});document.getElementById('play-animation').addEventListener('click',play);document.getElementById('pause-animation').addEventListener('click',pause);document.getElementById('reset-animation').addEventListener('click',reset);document.getElementById('sd-speed').addEventListener('change',event=>setSpeed(event.target.value));window.AetherVizRuntime={{play,pause,reset,setSpeed,update,getState}};render();window.__AETHERVIZ_RUNTIME_READY__=true}}catch(error){{window.__AETHERVIZ_RUNTIME_ERROR__=String(error&&error.message||error);caption.textContent='课件初始化失败：'+window.__AETHERVIZ_RUNTIME_ERROR__}}
}})();</script></body></html>"""
