"""Server-owned SVG runtime for finite discrete structures."""

from __future__ import annotations

import html
from typing import Any

from aetherviz_service.aetherviz.ir.discrete_structure.contract import compile_discrete_structure_ir


def assemble_discrete_structure_business_html(ir: dict[str, Any], plan: dict[str, Any], topic: str) -> str:
    compiled = compile_discrete_structure_ir(ir, plan)
    title = html.escape(str(plan.get("title") or topic or "离散结构"))
    goal = html.escape(str(plan.get("goal") or "观察有限对象的身份、顺序和拓扑变化。"))
    observation = html.escape(str(ir.get("observation") or "节点身份保持稳定，布局由运行时统一管理。"))
    animation = ir.get("animation") if isinstance(ir.get("animation"), dict) else {}
    variable = str(animation.get("variable") or "step")
    variables = {
        str(item.get("name")): item
        for item in ((plan.get("interactive_spec") or {}).get("variables", []))
        if isinstance(item, dict) and item.get("name") and not item.get("computed")
    }
    meta = variables.get(variable, {})
    label = html.escape(str(meta.get("label") or "阶段"))
    step = float(meta.get("step") or 1)
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>
.ds{{font-family:Inter,"PingFang SC",sans-serif;color:#202d36;background:#f4f8fb;padding:18px;min-height:100vh;box-sizing:border-box}}.ds h1{{margin:0;font-size:clamp(24px,4vw,38px)}}.ds-goal{{color:#60727e}}.ds-layout{{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:16px}}.ds-stage,.ds-side{{background:white;border:1px solid #d8e4eb;border-radius:18px;padding:14px}}#ds-svg{{width:100%;min-height:430px}}.ds-controls{{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:14px}}.ds-controls input{{flex:1;min-width:180px;accent-color:#347fa5}}button,select{{border:0;border-radius:9px;padding:9px 13px;background:#deedf5;color:#235c78}}.edge{{stroke:#7d98a8;stroke-width:2}}.node{{fill:#fff;stroke:#347fa5;stroke-width:3}}.node-label{{font-size:14px;fill:#20333e;text-anchor:middle;dominant-baseline:middle}}.set-box{{fill:#dff1eb;fill-opacity:.65;stroke:#3c8b74;stroke-width:2}}.sequence-line{{stroke:#347fa5;stroke-width:3}}@media(max-width:760px){{.ds-layout{{grid-template-columns:1fr}}}}
</style></head><body><main class="ds"><header data-region="learning-goal"><h1>{title}</h1><p class="ds-goal">{goal}</p></header><section class="ds-layout"><div class="ds-stage" id="aetherviz-stage"><svg id="ds-svg" data-role="main-visual" viewBox="0 0 760 450" role="img" aria-label="离散结构图"></svg></div><aside class="ds-side" data-region="caption"><h2 id="ds-view-title"></h2><p id="ds-detail"></p><p id="animation-caption">{observation}</p></aside></section><footer class="ds-controls control-panel" data-region="controls"><label for="ds-range">{label}</label><input id="ds-range" type="range" min="{float(animation.get("from", 0))}" max="{float(animation.get("to", 1))}" step="{step}" value="{float(animation.get("default", 0))}"><output id="ds-output"></output><select id="ds-view"></select><button id="play-animation">播放</button><button id="pause-animation">暂停</button><button id="reset-animation">重置</button><select id="ds-speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></footer></main><script id="discrete-structure-ir" type="application/json">{compiled}</script><script>
(()=>{{'use strict';const IR=JSON.parse(document.getElementById('discrete-structure-ir').textContent),svg=document.getElementById('ds-svg'),range=document.getElementById('ds-range'),output=document.getElementById('ds-output'),select=document.getElementById('ds-view'),detail=document.getElementById('ds-detail'),caption=document.getElementById('animation-caption'),title=document.getElementById('ds-view-title'),NS='http://www.w3.org/2000/svg';let controller,state=Number(IR.animation.default),view=IR.views[0].id;
function node(name,attrs={{}}){{const el=document.createElementNS(NS,name);for(const [key,value] of Object.entries(attrs))el.setAttribute(key,String(value));return el}}function text(x,y,value,cls='node-label'){{const el=node('text',{{x,y,class:cls}});el.textContent=value;svg.appendChild(el)}}function clear(){{while(svg.firstChild)svg.removeChild(svg.firstChild)}}function progress(){{return Math.max(0,Math.min(1,(state-IR.animation.from)/(IR.animation.to-IR.animation.from)))}}function visible(item,p){{return p>=Number(item.visible_from??0)&&p<=Number(item.visible_to??1)}}function visibleNodes(p){{return IR.nodes.filter(item=>visible(item,p)).sort((a,b)=>a.order-b.order)}}
function graphLayout(nodes,tree){{const positions=new Map();if(tree){{const root=(IR.views.find(item=>item.id===view)||{{}}).root,levels=new Map([[root,0]]);let changed=true;while(changed){{changed=false;IR.edges.forEach(edge=>{{if(levels.has(edge.source)&&!levels.has(edge.target)){{levels.set(edge.target,levels.get(edge.source)+1);changed=true}}}})}}const buckets=new Map();nodes.forEach(item=>{{const level=levels.get(item.id)||0;if(!buckets.has(level))buckets.set(level,[]);buckets.get(level).push(item)}});for(const [level,items] of buckets)items.forEach((item,index)=>positions.set(item.id,{{x:100+level*180,y:80+(index+1)*330/(items.length+1)}}))}}else nodes.forEach((item,index)=>{{const angle=-Math.PI/2+index*Math.PI*2/Math.max(1,nodes.length);positions.set(item.id,{{x:380+250*Math.cos(angle),y:225+160*Math.sin(angle)}})}});return positions}}
function renderGraph(tree=false){{const p=progress(),nodes=visibleNodes(p),ids=new Set(nodes.map(item=>item.id)),positions=graphLayout(nodes,tree);IR.edges.filter(item=>visible(item,p)&&ids.has(item.source)&&ids.has(item.target)).forEach(edge=>{{const a=positions.get(edge.source),b=positions.get(edge.target);svg.appendChild(node('line',{{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'edge'}}));if(edge.label)text((a.x+b.x)/2,(a.y+b.y)/2-8,edge.label)}});nodes.forEach(item=>{{const point=positions.get(item.id);svg.appendChild(node('circle',{{cx:point.x,cy:point.y,r:25,class:'node','data-node-id':item.id}}));text(point.x,point.y,item.label)}});detail.textContent=nodes.length+' 个可见节点，'+IR.edges.filter(item=>visible(item,p)&&ids.has(item.source)&&ids.has(item.target)).length+' 条可见边。'}}
function renderSet(ref){{const selected=IR.sets.find(item=>item.id===ref)||IR.sets[0],members=new Set(selected.members),nodes=visibleNodes(progress());svg.appendChild(node('rect',{{x:80,y:55,width:600,height:340,rx:80,class:'set-box'}}));text(110,85,selected.label);nodes.forEach((item,index)=>{{const inside=members.has(item.id),column=inside?0:1,row=inside?Array.from(members).indexOf(item.id):nodes.filter(node=>!members.has(node.id)).indexOf(item);const x=inside?220+(column%3)*130:570,y=135+(row%5)*52;svg.appendChild(node('circle',{{cx:x,cy:y,r:22,class:'node','data-node-id':item.id}}));text(x,y,item.label)}});detail.textContent=selected.label+' = {{'+nodes.filter(item=>members.has(item.id)).map(item=>item.label).join('，')+'}}'}}
function renderSequence(ref){{const sequence=IR.sequences.find(item=>item.id===ref)||IR.sequences[0],count=Math.max(1,Math.ceil(progress()*sequence.terms.length)),terms=sequence.terms.slice(0,count),w=620/Math.max(1,terms.length);svg.appendChild(node('line',{{x1:70,y1:225,x2:690,y2:225,class:'sequence-line'}}));terms.forEach((term,index)=>{{const x=70+w*(index+.5);svg.appendChild(node('circle',{{cx:x,cy:225,r:25,class:'node'}}));text(x,225,String(term));text(x,270,'a'+(index+1))}});detail.textContent=sequence.label+'：'+sequence.recurrence}}
function renderPermutation(){{const nodes=visibleNodes(progress()),shift=Math.floor(progress()*Math.max(1,nodes.length)),ordered=nodes.slice(shift).concat(nodes.slice(0,shift)),w=650/Math.max(1,ordered.length);ordered.forEach((item,index)=>{{const x=55+w*(index+.5);svg.appendChild(node('rect',{{x:x-28,y:190,width:56,height:56,rx:12,class:'node','data-node-id':item.id}}));text(x,218,item.label);text(x,275,String(index+1))}});detail.textContent='当前排列：'+ordered.map(item=>item.label).join(' → ')}}
function render(){{clear();const current=IR.views.find(item=>item.id===view)||IR.views[0];title.textContent=current.title;if(current.type==='graph')renderGraph(false);else if(current.type==='tree')renderGraph(true);else if(current.type==='set')renderSet(current.ref);else if(current.type==='sequence')renderSequence(current.ref);else renderPermutation();range.value=String(state);output.value=Number(state).toFixed(2);caption.textContent=IR.observation+' 当前阶段：'+output.value}}function setProgress(value){{state=IR.animation.from+(IR.animation.to-IR.animation.from)*Math.max(0,Math.min(1,Number(value)||0));render()}}function play(){{controller.play()}}function pause(){{controller.pause()}}function reset(){{controller.reset();state=Number(IR.animation.default);render()}}function setSpeed(value){{controller.setSpeed(Math.max(.25,Math.min(4,Number(value)||1)))}}function update(patch){{if(patch&&patch[IR.animation.variable]!=null)state=Math.max(IR.animation.from,Math.min(IR.animation.to,Number(patch[IR.animation.variable])));if(patch&&patch.view)view=String(patch.view);if(patch&&patch.speed!=null)setSpeed(patch.speed);render()}}function getState(){{return{{[IR.animation.variable]:state,view,visibleNodeIds:visibleNodes(progress()).map(item=>item.id)}}}}
try{{IR.views.forEach(item=>{{const option=document.createElement('option');option.value=item.id;option.textContent=item.title;select.appendChild(option)}});if(!window.AetherVizAnimationController)throw new Error('missing_animation_controller');controller=window.AetherVizAnimationController.create({{duration:Number(IR.animation.duration)||7,update:setProgress}});range.addEventListener('input',()=>{{pause();state=Number(range.value);render()}});select.addEventListener('change',()=>{{view=select.value;render()}});document.getElementById('play-animation').addEventListener('click',play);document.getElementById('pause-animation').addEventListener('click',pause);document.getElementById('reset-animation').addEventListener('click',reset);document.getElementById('ds-speed').addEventListener('change',event=>setSpeed(event.target.value));window.AetherVizRuntime={{play,pause,reset,setSpeed,update,getState}};render();window.__AETHERVIZ_RUNTIME_READY__=true}}catch(error){{window.__AETHERVIZ_RUNTIME_ERROR__=String(error&&error.message||error);caption.textContent='课件初始化失败：'+window.__AETHERVIZ_RUNTIME_ERROR__}}
}})();</script></body></html>'''
