"""Server-owned SVG runtime for constraint geometry IR."""

from __future__ import annotations

import html
import json
from typing import Any

from aetherviz_service.aetherviz.ir.constraint_geometry.contract import compile_constraint_geometry_ir


def assemble_constraint_geometry_business_html(ir: dict[str, Any], plan: dict[str, Any], topic: str) -> str:
    compiled = compile_constraint_geometry_ir(ir, plan)
    title = html.escape(str(plan.get("title") or topic or "互动几何构造"))
    goal = html.escape(str(plan.get("goal") or "观察几何对象在变化中保持的约束关系。"))
    animation = ir.get("animation") if isinstance(ir.get("animation"), dict) else {}
    variable = str(animation.get("variable") or "参数")
    variables = {
        str(item.get("name")): item
        for item in ((plan.get("interactive_spec") or {}).get("variables", []))
        if isinstance(item, dict) and item.get("name")
    }
    state_meta = variables.get(variable, {})
    state_label = html.escape(str(state_meta.get("label") or variable))
    state_step = float(
        state_meta.get("step") or (float(animation.get("to", 1)) - float(animation.get("from", 0))) / 100
    )
    observation = html.escape(str(ir.get("observation") or "观察约束关系在参数变化中保持成立。"))
    initial_state = {
        name: float(item.get("default", item.get("min", 0)))
        for name, item in variables.items()
        if not item.get("computed")
    }
    initial_state[variable] = float(animation.get("default", animation.get("from", 0)))
    initial_state_json = json.dumps(initial_state, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    state_bounds = {
        name: {
            "min": float(item.get("min", 0)),
            "max": float(item.get("max", 1)),
            "default": float(item.get("default", item.get("min", 0))),
            "unit": str(item.get("unit") or ""),
        }
        for name, item in variables.items()
        if not item.get("computed")
    }
    state_bounds_json = json.dumps(state_bounds, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>
.cg{{color:#17352d;background:#f7fbf9;font-family:Inter,"PingFang SC",sans-serif;padding:18px}}.cg-head{{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}}.cg-head h1{{margin:0 0 6px;font-size:clamp(22px,3vw,34px)}}.cg-head p{{margin:0;color:#526d65}}.cg-badge{{padding:6px 10px;border-radius:999px;background:#dff3ea;color:#176b54;font-size:13px}}.cg-workspace{{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:16px;margin-top:14px}}.cg-stage{{min-height:430px;border:1px solid #d5e6df;border-radius:18px;background:#fff;overflow:hidden}}#constraint-geometry-svg{{display:block;width:100%;height:100%;min-height:430px;touch-action:none}}.cg-panel{{border:1px solid #d5e6df;border-radius:18px;background:#fff;padding:16px}}.cg-panel h2{{font-size:16px;margin:0 0 10px}}.cg-panel ul{{padding-left:20px;margin:0 0 16px;color:#49625b}}.cg-caption{{line-height:1.7;color:#23483d}}.cg-controls{{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:14px}}.cg-controls input{{flex:1;min-width:180px}}.cg-line{{stroke:#2c7a68;stroke-width:3;vector-effect:non-scaling-stroke}}.cg-circle{{fill:none;stroke:#5d7fc4;stroke-width:3;vector-effect:non-scaling-stroke}}.cg-point{{fill:#ef8354;stroke:#fff;stroke-width:2;vector-effect:non-scaling-stroke}}.cg-point[data-draggable="true"]{{cursor:grab;stroke:#9a3f1f;stroke-width:3}}.cg-point[data-dragging="true"]{{cursor:grabbing}}.cg-label,.cg-angle-label{{font-size:16px;fill:#17352d;paint-order:stroke;stroke:#fff;stroke-width:4;stroke-linejoin:round}}.cg-angle{{fill:none;stroke:#d97706;stroke-width:3;vector-effect:non-scaling-stroke}}.cg-locus{{fill:none;stroke:#8b5cf6;stroke-width:2.5;stroke-dasharray:5 4;vector-effect:non-scaling-stroke}}@media(max-width:760px){{.cg-workspace{{grid-template-columns:1fr}}.cg-stage,#constraint-geometry-svg{{min-height:350px}}}}
</style></head><body><main class="cg"><header class="cg-head" data-region="learning-goal"><div><h1>{title}</h1><p>{goal}</p></div><span class="cg-badge">约束几何 IR</span></header><section class="cg-workspace"><div class="cg-stage" id="aetherviz-stage"><svg id="constraint-geometry-svg" data-role="main-visual" viewBox="0 0 760 520" role="img" aria-label="参数化几何构造"><g id="cg-grid"></g><g id="cg-loci"></g><g id="cg-circles"></g><g id="cg-lines"></g><g id="cg-angles"></g><g id="cg-points"></g><g id="cg-labels"></g></svg></div><aside class="cg-panel" data-region="caption"><h2>始终成立的关系</h2><ul id="cg-constraints"></ul><p id="animation-caption" class="cg-caption">{observation}</p></aside></section><footer class="cg-controls control-panel" data-region="controls"><label for="cg-range">{state_label}</label><input id="cg-range" type="range" min="{float(animation.get("from", 0))}" max="{float(animation.get("to", 1))}" step="{state_step}"><output id="cg-output"></output><button id="play-animation" type="button">播放</button><button id="pause-animation" type="button">暂停</button><button id="reset-animation" type="button">重置</button><select id="cg-speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></footer><section data-region="formula"><p>图形位置由统一状态模型计算，约束在整个参数范围内经过服务端采样验证。</p></section></main>
<script id="constraint-geometry-ir" type="application/json">{compiled}</script><script>
(()=>{{'use strict';const IR=JSON.parse(document.getElementById('constraint-geometry-ir').textContent);const BOUNDS={state_bounds_json};const NS='http://www.w3.org/2000/svg';const svg=document.getElementById('constraint-geometry-svg');const lineLayer=document.getElementById('cg-lines');const circleLayer=document.getElementById('cg-circles');const angleLayer=document.getElementById('cg-angles');const locusLayer=document.getElementById('cg-loci');const pointLayer=document.getElementById('cg-points');const labelLayer=document.getElementById('cg-labels');const range=document.getElementById('cg-range');const output=document.getElementById('cg-output');const caption=document.getElementById('animation-caption');const state={initial_state_json};range.value=String(state[IR.animation.variable]);let controller=null,activeDrag=null;const pointNodes=new Map(),lineNodes=new Map(),circleNodes=new Map(),angleNodes=new Map(),locusNodes=new Map(),locusSamples=new Map(),labelNodes=new Map();
function node(tag,attrs,parent){{const el=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs||{{}}))el.setAttribute(key,String(value));(parent||svg).appendChild(el);return el;}}
function evaluate(expr){{if(typeof expr==='number')return expr;if(expr&&Object.prototype.hasOwnProperty.call(expr,'state'))return Number(state[expr.state]);const values=(expr.args||[]).map(evaluate);switch(expr.op){{case'add':return values.reduce((a,b)=>a+b,0);case'sub':return values.slice(1).reduce((a,b)=>a-b,values[0]);case'mul':return values.reduce((a,b)=>a*b,1);case'div':return values.slice(1).reduce((a,b)=>a/b,values[0]);case'pow':return Math.pow(values[0],values[1]);case'min':return Math.min(...values);case'max':return Math.max(...values);case'neg':return-values[0];case'abs':return Math.abs(values[0]);case'sqrt':return Math.sqrt(values[0]);case'sin':return Math.sin(values[0]);case'cos':return Math.cos(values[0]);case'tan':return Math.tan(values[0]);case'asin':return Math.asin(values[0]);case'acos':return Math.acos(values[0]);case'atan2':return Math.atan2(values[0],values[1]);case'deg_to_rad':return values[0]*Math.PI/180;default:throw new Error('invalid_constraint_geometry_expression');}}}}
const vp=IR.viewport,scale=Math.min(672/(vp.x_max-vp.x_min),432/(vp.y_max-vp.y_min)),offsetX=(760-(vp.x_max-vp.x_min)*scale)/2,offsetY=(520-(vp.y_max-vp.y_min)*scale)/2;function map(x,y){{return{{x:offsetX+(x-vp.x_min)*scale,y:520-offsetY-(y-vp.y_min)*scale}};}}
function build(){{IR.lines.forEach(item=>lineNodes.set(item.id,node('line',{{class:'cg-line','data-object':item.id}},lineLayer)));IR.circles.forEach(item=>circleNodes.set(item.id,node('circle',{{class:'cg-circle','data-object':item.id}},circleLayer)));IR.loci.forEach(item=>{{locusNodes.set(item.id,node('path',{{class:'cg-locus','data-object':item.id}},locusLayer));locusSamples.set(item.id,[]);}});IR.angles.forEach(item=>{{const arc=node('path',{{class:'cg-angle','data-object':item.id}},angleLayer),label=node('text',{{class:'cg-angle-label'}},angleLayer);angleNodes.set(item.id,{{arc,label}});}});IR.points.forEach(item=>{{const dot=node('circle',{{r:6,class:'cg-point','data-object':item.id,'data-draggable':Boolean(item.drag)}},pointLayer);pointNodes.set(item.id,dot);if(item.drag)dot.addEventListener('pointerdown',event=>startDrag(event,item,dot));const label=node('text',{{class:'cg-label','data-object-label':item.id}},labelLayer);label.textContent=item.label;labelNodes.set(item.id,label);}});const names={{coincident:'点重合',horizontal:'保持水平',vertical:'保持竖直',parallel:'保持平行',perpendicular:'保持垂直',equal_length:'保持等长',point_on_circle:'点始终在圆上',midpoint:'保持中点',collinear:'保持共线',tangent:'保持相切',equal_angle:'保持等角',supplementary:'保持互补'}};const list=document.getElementById('cg-constraints');IR.constraints.forEach(item=>{{const li=document.createElement('li');li.textContent=(names[item.type]||item.type)+'：'+item.refs.join('、');list.appendChild(li);}});}}
function angleValue(a,v,b){{const ux=a.x-v.x,uy=a.y-v.y,vx=b.x-v.x,vy=b.y-v.y;return Math.acos(Math.max(-1,Math.min(1,(ux*vx+uy*vy)/(Math.hypot(ux,uy)*Math.hypot(vx,vy)))));}}
function derive(){{const points=new Map(IR.points.map(item=>[item.id,{{...item,x:evaluate(item.x),y:evaluate(item.y)}}]));const lines=IR.lines.map(item=>({{...item,a:points.get(item.from),b:points.get(item.to)}}));const circles=IR.circles.map(item=>({{...item,center:points.get(item.center),radius:evaluate(item.radius)}}));const angles=IR.angles.map(item=>({{...item,a:points.get(item.from),v:points.get(item.vertex),b:points.get(item.to),value:angleValue(points.get(item.from),points.get(item.vertex),points.get(item.to))}}));return{{points,lines,circles,angles}};}}
function renderAngle(item){{const a=map(item.a.x,item.a.y),v=map(item.v.x,item.v.y),b=map(item.b.x,item.b.y),entry=angleNodes.get(item.id),radius=30,start=Math.atan2(a.y-v.y,a.x-v.x),end=Math.atan2(b.y-v.y,b.x-v.x);let delta=end-start;while(delta>Math.PI)delta-=Math.PI*2;while(delta< -Math.PI)delta+=Math.PI*2;const p1={{x:v.x+radius*Math.cos(start),y:v.y+radius*Math.sin(start)}},p2={{x:v.x+radius*Math.cos(start+delta),y:v.y+radius*Math.sin(start+delta)}},sweep=delta>=0?1:0,mid=start+delta/2;entry.arc.setAttribute('d','M '+p1.x+' '+p1.y+' A '+radius+' '+radius+' 0 0 '+sweep+' '+p2.x+' '+p2.y);entry.label.setAttribute('x',v.x+(radius+17)*Math.cos(mid));entry.label.setAttribute('y',v.y+(radius+17)*Math.sin(mid));entry.label.textContent=item.label+' '+(item.value*180/Math.PI).toFixed(item.precision)+'°';}}
function recordLoci(view){{for(const item of IR.loci){{const point=view.points.get(item.point),samples=locusSamples.get(item.id),last=samples[samples.length-1];if(!last||Math.hypot(point.x-last.x,point.y-last.y)>=item.min_distance){{samples.push({{x:point.x,y:point.y}});if(samples.length>item.max_samples)samples.shift();}}const path=samples.map((sample,index)=>{{const p=map(sample.x,sample.y);return(index?'L ':'M ')+p.x+' '+p.y;}}).join(' ');locusNodes.get(item.id).setAttribute('d',path);}}}}
function render(record=true){{const view=derive();for(const item of view.lines){{const a=map(item.a.x,item.a.y),b=map(item.b.x,item.b.y),el=lineNodes.get(item.id);el.setAttribute('x1',a.x);el.setAttribute('y1',a.y);el.setAttribute('x2',b.x);el.setAttribute('y2',b.y);}}for(const item of view.circles){{const center=map(item.center.x,item.center.y),el=circleNodes.get(item.id);el.setAttribute('cx',center.x);el.setAttribute('cy',center.y);el.setAttribute('r',item.radius*scale);}}for(const item of view.angles)renderAngle(item);for(const item of view.points.values()){{const p=map(item.x,item.y),dot=pointNodes.get(item.id),label=labelNodes.get(item.id);dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);label.setAttribute('x',p.x+9);label.setAttribute('y',p.y-9);}}if(record)recordLoci(view);range.value=String(state[IR.animation.variable]);output.value=Number(state[IR.animation.variable]).toFixed(2);caption.textContent=IR.observation+' 当前参数：'+output.value;return view;}}
function clampState(name,value){{const bound=BOUNDS[name];return bound?Math.max(bound.min,Math.min(bound.max,value)):value;}}function pointerToMath(event){{const rect=svg.getBoundingClientRect(),sx=(event.clientX-rect.left)*760/rect.width,sy=(event.clientY-rect.top)*520/rect.height;return{{x:vp.x_min+(sx-offsetX)/scale,y:vp.y_min+(520-offsetY-sy)/scale}};}}function startDrag(event,item,dot){{if(!item.drag)return;controller.pause();activeDrag={{item,dot,pointerId:event.pointerId}};dot.setAttribute('data-dragging','true');dot.setPointerCapture(event.pointerId);event.preventDefault();}}function moveDrag(event){{if(!activeDrag||event.pointerId!==activeDrag.pointerId)return;const drag=activeDrag.item.drag,p=pointerToMath(event),view=derive();let value;if(drag.mode==='x')value=p.x;else if(drag.mode==='y')value=p.y;else if(drag.mode==='angle_on_circle'){{const circle=view.circles.find(item=>item.id===drag.ref);if(!circle)return;value=Math.atan2(p.y-circle.center.y,p.x-circle.center.x);if(drag.unit==='degree'||String((BOUNDS[drag.state]||{{}}).unit).match(/°|deg|degree/))value=value*180/Math.PI;}}else if(drag.mode==='segment_parameter'){{const line=view.lines.find(item=>item.id===drag.ref);if(!line)return;const dx=line.b.x-line.a.x,dy=line.b.y-line.a.y,t=Math.max(0,Math.min(1,((p.x-line.a.x)*dx+(p.y-line.a.y)*dy)/(dx*dx+dy*dy))),bound=BOUNDS[drag.state];value=bound?bound.min+(bound.max-bound.min)*t:t;}}state[drag.state]=clampState(drag.state,value);render();event.preventDefault();}}function endDrag(event){{if(!activeDrag||event.pointerId!==activeDrag.pointerId)return;activeDrag.dot.removeAttribute('data-dragging');activeDrag=null;}}
function clearLoci(){{for(const samples of locusSamples.values())samples.length=0;for(const path of locusNodes.values())path.setAttribute('d','');}}function setProgress(progress){{state[IR.animation.variable]=IR.animation.from+(IR.animation.to-IR.animation.from)*Math.max(0,Math.min(1,progress));render();}}function play(){{controller.play();}}function pause(){{controller.pause();}}function reset(){{controller.reset();for(const [name,bound] of Object.entries(BOUNDS))state[name]=bound.default;clearLoci();render(false);}}function setSpeed(value){{controller.setSpeed(Math.max(.25,Math.min(4,Number(value)||1)));}}function update(patch){{if(patch&&typeof patch==='object')for(const [key,value] of Object.entries(patch))if(Object.prototype.hasOwnProperty.call(state,key))state[key]=clampState(key,Number(value));if(patch&&patch.speed!=null)setSpeed(patch.speed);render();}}function getState(){{return{{...state,locusSampleCounts:Object.fromEntries(Array.from(locusSamples,([key,value])=>[key,value.length]))}};}}
function handleWidgetAction(event){{const data=event.data||{{}};if(data.type==='SET_WIDGET_STATE')update(data.state||data.payload||{{}});else if(data.type==='HIGHLIGHT_ELEMENT'){{const target=document.querySelector(data.selector||'');if(target)target.style.filter='drop-shadow(0 0 6px #f59e0b)';}}else if(data.type==='ANNOTATE_ELEMENT')caption.textContent=String(data.text||data.annotation||caption.textContent);}}
try{{build();if(!window.AetherVizAnimationController)throw new Error('missing_animation_controller');controller=window.AetherVizAnimationController.create({{duration:Number(IR.animation.duration)||6,update:setProgress}});range.addEventListener('input',()=>{{controller.pause();state[IR.animation.variable]=Number(range.value);render();}});svg.addEventListener('pointermove',moveDrag);svg.addEventListener('pointerup',endDrag);svg.addEventListener('pointercancel',endDrag);document.getElementById('play-animation').addEventListener('click',play);document.getElementById('pause-animation').addEventListener('click',pause);document.getElementById('reset-animation').addEventListener('click',reset);document.getElementById('cg-speed').addEventListener('change',event=>setSpeed(event.target.value));window.addEventListener('message',handleWidgetAction);window.AetherVizRuntime={{play,pause,reset,setSpeed,update,getState,clearLoci}};render();window.__AETHERVIZ_RUNTIME_READY__=true;}}catch(error){{window.__AETHERVIZ_RUNTIME_ERROR__=String(error&&error.message||error);caption.textContent='课件初始化失败：'+window.__AETHERVIZ_RUNTIME_ERROR__;}}
}})();</script></body></html>"""
