"""Server-owned SVG runtime for parametric regular-polygon geometry."""

from __future__ import annotations

import html
import json
from typing import Any

from aetherviz_service.aetherviz.ir.parametric_geometry.contract import compile_parametric_geometry_ir


def assemble_parametric_geometry_business_html(ir: dict[str, Any], plan: dict[str, Any], topic: str) -> str:
    compiled = compile_parametric_geometry_ir(ir, plan)
    title = html.escape(str(topic or "参数几何构造"))
    goal = html.escape(str(plan.get("goal") or "观察离散参数变化时几何量如何收敛"))
    config = json.dumps(
        {
            "type": str(plan.get("interactive_type") or "simulation"),
            "version": "1.0",
            "defaults": {ir["state"]["variable"]: ir["state"]["default"], "speed": 1},
        },
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")
    return f"""<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>
*{{box-sizing:border-box}}body{{margin:0;background:#f8fafc;color:#172033;font-family:Inter,"PingFang SC",sans-serif}}.pg{{min-height:560px;display:grid;grid-template-rows:auto 1fr auto;gap:12px;padding:16px}}.pg-head{{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}}h1{{font-size:22px;margin:0 0 5px}}.goal{{margin:0;color:#526077;font-size:14px}}.badge{{padding:6px 10px;border-radius:999px;background:#e8eefc;color:#3156a3;font-size:12px;white-space:nowrap}}.workspace{{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:14px;min-height:0}}.stage{{min-width:0;border:1px solid #dbe3f0;border-radius:16px;background:#fff;overflow:hidden}}svg{{display:block;width:100%;height:100%;min-height:390px}}.panel{{display:flex;flex-direction:column;gap:10px;padding:14px;border:1px solid #dbe3f0;border-radius:16px;background:#fff}}.metric{{padding:10px;border-radius:10px;background:#f3f6fb}}.metric span{{display:block;color:#67748a;font-size:12px}}.metric strong{{font-variant-numeric:tabular-nums;font-size:18px}}.legend{{display:flex;flex-wrap:wrap;gap:8px;font-size:12px}}.legend i{{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:4px}}.controls{{display:grid;grid-template-columns:auto 1fr auto auto auto;gap:10px;align-items:center}}input[type=range]{{width:100%}}button{{border:1px solid #ccd6e6;background:#fff;color:#26354e;border-radius:9px;padding:8px 12px;cursor:pointer}}button:hover{{background:#eef3fb}}select{{border:1px solid #ccd6e6;border-radius:9px;padding:8px;background:#fff}}@media(max-width:760px){{.workspace{{grid-template-columns:1fr}}.panel{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}}.controls{{grid-template-columns:auto 1fr auto;}}}}
</style></head><body><main class="pg"><header class="pg-head" data-region="learning-goal"><div><h1>{title}</h1><p>{goal}</p></div><span class="badge">参数几何 IR</span></header><section class="workspace"><div class="stage" id="aetherviz-stage"><svg id="geometry" data-role="main-visual" viewBox="0 0 680 500" role="img" aria-label="参数化圆与正多边形"><g id="grid"></g><circle id="base-circle" cx="300" cy="250" r="120" fill="none" stroke="#94a3b8" stroke-width="2"/><g id="polygons"></g><text id="scene-label" x="300" y="472" text-anchor="middle" fill="#526077" font-size="15"></text></svg></div><aside class="panel" data-region="caption"><div id="metrics"></div><div class="legend" id="legend"></div><p id="observation" class="goal"></p></aside></section><footer class="controls" data-region="controls"><label id="state-label" for="state-range"></label><input id="state-range" type="range"><output id="state-output"></output><button id="play-animation" type="button">播放</button><button id="pause-animation" type="button">暂停</button><button id="reset-animation" type="button">重置</button><select id="speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></footer><section data-region="formula"><p>正多边形周长随边数变化并逼近圆周长。</p></section><ol data-region="teaching-flow"><li data-step="1">调节边数</li><li data-step="2">比较内接与外切周长</li><li data-step="3">观察误差收敛</li></ol></main>
<script id="widget-config" type="application/json">{config}</script><script id="parametric-geometry-ir" type="application/json">{compiled}</script>
<script>
(()=>{{'use strict';const IR=JSON.parse(document.getElementById('parametric-geometry-ir').textContent);const NS='http://www.w3.org/2000/svg';const cx=300,cy=250,screenRadius=120;const range=document.getElementById('state-range');const output=document.getElementById('state-output');const polygonsRoot=document.getElementById('polygons');const metricsRoot=document.getElementById('metrics');const legend=document.getElementById('legend');const observation=document.getElementById('observation');const sceneLabel=document.getElementById('scene-label');let controller=null;let speed=1;const state={{[IR.state.variable]:IR.state.default}};const registries=new Map();
function svg(name,attrs){{const node=document.createElementNS(NS,name);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,String(value)));return node;}}
function buildScene(){{IR.polygons.forEach(poly=>{{const group=svg('g',{{'data-polygon':poly.id}});const edges=[];for(let i=0;i<IR.state.maximum;i++){{const edge=svg('line',{{stroke:poly.color,'stroke-width':3,'stroke-linecap':'round','vector-effect':'non-scaling-stroke'}});group.appendChild(edge);edges.push(edge);}}polygonsRoot.appendChild(group);registries.set(poly.id,edges);const item=document.createElement('span');item.innerHTML='<i style="background:'+poly.color+'"></i>'+poly.label;legend.appendChild(item);}});IR.measures.forEach(measure=>{{const card=document.createElement('div');card.className='metric';card.innerHTML='<span></span><strong></strong>';card.firstChild.textContent=measure.label;card.dataset.measure=measure.id;metricsRoot.appendChild(card);}});range.min=IR.state.minimum;range.max=IR.state.maximum;range.step=IR.state.step;document.getElementById('state-label').textContent=IR.state.label;}}
function perimeter(poly,n){{const r=IR.circle.radius;return poly.mode==='inscribed'?2*n*r*Math.sin(Math.PI/n):2*n*r*Math.tan(Math.PI/n);}}
function valueFor(measure,n){{const circumference=2*Math.PI*IR.circle.radius;if(measure.type==='circle_circumference')return circumference;const poly=IR.polygons.find(item=>item.id===measure.polygon);const p=perimeter(poly,n);if(measure.type==='polygon_perimeter')return p;if(measure.type==='relative_error')return Math.abs(p-circumference)/circumference;return Math.abs(p-circumference);}}
function deriveView(){{const raw=Number(state[IR.state.variable]);const n=Math.max(IR.state.minimum,Math.min(IR.state.maximum,Math.round(raw/IR.state.step)*IR.state.step));return{{n,polygons:IR.polygons.map(poly=>{{const radius=poly.mode==='circumscribed'?screenRadius/Math.cos(Math.PI/n):screenRadius;const points=Array.from({{length:n}},(_,i)=>{{const angle=-Math.PI/2+i*Math.PI*2/n;return[cx+radius*Math.cos(angle),cy+radius*Math.sin(angle)];}});return{{poly,points}};}}),metrics:IR.measures.map(measure=>({{measure,value:valueFor(measure,n)}}))}};}}
function applyView(view){{state[IR.state.variable]=view.n;range.value=String(view.n);output.value=String(view.n)+(IR.state.unit||'');sceneLabel.textContent=IR.state.label+' = '+view.n;view.polygons.forEach(item=>{{const edges=registries.get(item.poly.id);for(let i=0;i<edges.length;i++){{const edge=edges[i];if(i<item.points.length){{const a=item.points[i],b=item.points[(i+1)%item.points.length];edge.setAttribute('x1',a[0].toFixed(3));edge.setAttribute('y1',a[1].toFixed(3));edge.setAttribute('x2',b[0].toFixed(3));edge.setAttribute('y2',b[1].toFixed(3));edge.style.display='';}}else edge.style.display='none';}}}});view.metrics.forEach(item=>{{const node=metricsRoot.querySelector('[data-measure="'+item.measure.id+'"] strong');node.textContent=Number(item.value).toFixed(item.measure.precision);}});observation.textContent='边数增加时，正多边形的边界量逐步逼近圆的对应量。';}}
function render(){{applyView(deriveView());}}function setProgress(progress){{const span=IR.state.maximum-IR.state.minimum;state[IR.state.variable]=IR.state.minimum+span*Math.max(0,Math.min(1,progress));render();}}function play(){{controller.play();}}function pause(){{controller.pause();}}function reset(){{controller.reset();state[IR.state.variable]=IR.state.default;render();}}function setSpeed(value){{speed=Math.max(.25,Math.min(4,Number(value)||1));controller.setSpeed(speed);}}function update(patch){{if(patch&&Object.prototype.hasOwnProperty.call(patch,IR.state.variable))state[IR.state.variable]=Number(patch[IR.state.variable]);if(patch&&patch.speed!=null)setSpeed(patch.speed);render();}}function getState(){{return{{...state,speed}};}}function handleWidgetAction(event){{const data=event.data||{{}};if(data.type==='SET_WIDGET_STATE')update(data.state||data.payload||{{}});else if(data.type==='HIGHLIGHT_ELEMENT'){{const node=document.querySelector(data.selector||'');if(node)node.style.filter='drop-shadow(0 0 6px #f59e0b)';}}else if(data.type==='ANNOTATE_ELEMENT')observation.textContent=String(data.text||data.annotation||observation.textContent);else if(data.type==='REVEAL_ELEMENT'){{const node=document.querySelector(data.selector||'');if(node)node.hidden=false;}}}}
buildScene();if(!window.AetherVizAnimationController)throw new Error('missing_animation_controller');controller=window.AetherVizAnimationController.create({{duration:Number(IR.animation.duration)||6,update:setProgress}});range.addEventListener('input',()=>{{controller.pause();state[IR.state.variable]=Number(range.value);render();}});document.getElementById('play-animation').addEventListener('click',play);document.getElementById('pause-animation').addEventListener('click',pause);document.getElementById('reset-animation').addEventListener('click',reset);document.getElementById('speed').addEventListener('change',event=>setSpeed(event.target.value));window.addEventListener('message',handleWidgetAction);window.AetherVizRuntime={{play,pause,reset,setSpeed,update,getState}};render();window.__AETHERVIZ_RUNTIME_READY__=true;
}})();
</script></body></html>"""
